export const mcdonaldsMenu = [
    { id: 1, name: "Big Mac" },
    { id: 2, name: "Cheeseburger" },
    { id: 3, name: "Quarter Pounder with Cheese" },
    { id: 4, name: "Filet-O-Fish" },
    { id: 5, name: "McChicken" },
    { id: 6, name: "Chicken McNuggets" },
    { id: 7, name: "McDouble" },
    { id: 8, name: "Double Cheeseburger" },
    { id: 9, name: "Bacon McDouble" },
    { id: 10, name: "Spicy McChicken" },
    { id: 11, name: "Crispy Chicken Sandwich" },
    { id: 12, name: "Egg McMuffin" },
    { id: 13, name: "Sausage McMuffin" },
    { id: 14, name: "Sausage Biscuit" },
    { id: 15, name: "Hotcakes and Sausage" },
    { id: 16, name: "Bacon, Egg & Cheese Biscuit" },
    { id: 17, name: "Hash Browns" },
    { id: 18, name: "McGriddles" },
    { id: 19, name: "McFlurry Oreo" },
    { id: 20, name: "McFlurry M&M's" },
    { id: 21, name: "Apple Pie" },
    { id: 22, name: "Chocolate Shake" },
    { id: 23, name: "Vanilla Shake" },
    { id: 24, name: "Strawberry Shake" },
    { id: 25, name: "French Fries" },
    { id: 26, name: "Chicken Caesar Salad" },
    { id: 27, name: "Fruit & Yogurt Parfait" },
    { id: 28, name: "Deluxe Crispy Chicken Sandwich" },
    { id: 29, name: "Chicken Tenders" },
    { id: 30, name: "Spicy Deluxe Crispy Chicken Sandwich" }
];
