import {ColorKey} from "@/components/ui/Badge";

export const statusColors: Record<string, ColorKey> = {
    Active: 'blue',
    Inactive: 'gray',
};

export const paymentColors: Record<string, ColorKey> = {
    Paid: 'green',
    Unpaid: 'red',
};

export type tableDataType = {
    id:number,
    name:string,
    email:string,
    userStatus: string,
    lastLogin: string,
    paymentStatus: string,
    paymentDate: string,
    amount: number,
    currency: string,
}

const tableData:tableDataType[] = [
    {
        id: 1,
        name: 'Erin Levin',
        email: 'samegmail@gmail.com',
        userStatus: 'Active',
        lastLogin: '2024-09-26',
        paymentStatus: 'Paid',
        paymentDate: '2024-09-27',
        amount: 200,
        currency: 'USD',
    },
    {
        id: 2,
        name: 'John Doe',
        email: 'somegmail2@gmail.com',
        userStatus: 'Inactive',
        lastLogin: '2024-09-24',
        paymentStatus: 'Unpaid',
        paymentDate: '2024-09-24',
        amount: 150,
        currency: 'USD',
    },
    {
        id: 3,
        name: 'Alice Johnson',
        email: 'somegmail3@gmail.com',
        userStatus: 'Active',
        lastLogin: '2024-09-26',
        paymentStatus: 'Paid',
        paymentDate: '2024-09-26',
        amount: 300,
        currency: 'USD',
    },
    {
        id: 4,
        name: 'Michael Brown',
        email: 'aomegmail4@gmail.com',
        userStatus: 'Active',
        lastLogin: '2024-09-27',
        paymentStatus: 'Unpaid',
        paymentDate: '2024-09-27',
        amount: 400,
        currency: 'USD',
    },
    {
        id: 5,
        name: 'Linda White',
        email: 'somegmail5@gmail.com',
        userStatus: 'Active',
        lastLogin: '2024-09-27',
        paymentStatus: 'Paid',
        paymentDate: '2024-09-26',
        amount: 250,
        currency: 'USD',
    },
    {
        id: 6,
        name: 'Chris Evans',
        email: 'bomegmail6@gmail.com',
        userStatus: 'Inactive',
        lastLogin: '2024-09-23',
        paymentStatus: 'Unpaid',
        paymentDate: '2024-09-23',
        amount: 175,
        currency: 'USD',
    },
    {
        id: 7,
        name: 'Diana Prince',
        email: 'domegmail7@gmail.com',
        userStatus: 'Active',
        lastLogin: '2024-09-27',
        paymentStatus: 'Paid',
        paymentDate: '2024-09-25',
        amount: 500,
        currency: 'USD',
    },
    {
        id: 8,
        name: 'Bruce Wayne',
        email: 'momegmail8@gmail.com',
        userStatus: 'Active',
        lastLogin: '2024-09-28',
        paymentStatus: 'Paid',
        paymentDate: '2024-09-28',
        amount: 600,
        currency: 'USD',
    },
    {
        id: 9,
        name: 'Peter Parker',
        email: 'eomegmail9@gmail.com',
        userStatus: 'Inactive',
        lastLogin: '2024-09-26',
        paymentStatus: 'Unpaid',
        paymentDate: '2024-09-26',
        amount: 50,
        currency: 'USD',
    },
    {
        id: 10,
        name: 'Clark Kent',
        email: 'aomegmail10@gmail.com',
        userStatus: 'Active',
        lastLogin: '2024-09-28',
        paymentStatus: 'Paid',
        paymentDate: '2024-09-28',
        amount: 700,
        currency: 'USD',
    },
    ...Array.from({ length: 10 }).map((_, index) => ({
        id: 11 + index,
        name: `User ${11 + index}`,
        email: `somegmail${11 + index}@gmail.com`,
        userStatus: index % 2 === 0 ? 'Active' : 'Inactive',
        lastLogin: `2024-09-${25 + (index % 5)}`,
        paymentStatus: index % 2 === 0 ? 'Paid' : 'Unpaid',
        paymentDate: `2024-09-${25 + (index % 5)}`,
        amount: 100 + index * 50,
        currency: 'USD',
    })),
];

export default tableData;
